name: Continuous Integration

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run tests
        id: test
        run: |
          tap_output=$(npx mocha markdownParser.test --reporter tap)
          passing_tests=$(echo "$tap_output" | grep -oP '(?<=# pass )\d+' | tail -1)
          total_tests=$(echo "$tap_output" | grep -oP '(?<=# tests )\d+' | tail -1)
          echo "PASSING_TESTS=$passing_tests" >> $GITHUB_ENV
          echo "TOTAL_TESTS=$total_tests" >> $GITHUB_ENV
          echo "TAP_OUTPUT=$tap_output" >> $GITHUB_ENV

      - name: Create status badge
        env:
          USERNAME: ${{ github.repository_owner }}
          REPOSITORY: ${{ github.repository }}
          PASSING_TESTS: ${{ env.PASSING_TESTS }}
          TOTAL_TESTS: ${{ env.TOTAL_TESTS }}
        run: echo "[![CI](https://img.shields.io/badge/CI-$PASSING_TESTS/$TOTAL_TESTS-brightgreen)](https://github.com/$USERNAME/$REPOSITORY/actions/workflows/ci.yml)"
